### ISSUE TITLE
User can sign up & login

### ISSUE THREAD

**Issue by rjbae** [rjbae/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can login to an existing account or sign up for a new one.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User will first land on the home page.
- User will click on Signup in the top right corner.
- User will be redirected to the sign-up page.
- Form re-renders to the sign-up page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-07-26 at 11 34 39 AM](https://user-images.githubusercontent.com/96757366/181084962-8669c881-aadd-4793-b031-a7337b9f52fa.png)
![Screen Shot 2022-07-26 at 11 35 41 AM](https://user-images.githubusercontent.com/96757366/181085123-9db54663-6fcb-4cde-bb13-05512b7d8bb9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle a POST request to /api/auth/sign-up
- [x] Insert into users table under the username and password columns.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a sign up component.
- [x] Assign an empty string to username and password property to this.state.
- [x] Create a handleChange method that sets the state of username and password
- [x] Create a handleSubmit method that adds the request object and fetches /api/auth/sign-up
- [x] Render a sign up page.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
